name: travel_app5b
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/img1.jpg
    - assets/img/img2.jpg
    - assets/img/img3.jpg
    - assets/img/img4.jpeg
    - assets/img/imge1.jpg
    - assets/img/imge2.jpg
    - assets/img/imge3.jpg
    - assets/img/imge4.jpg